import { SensitiveElementType } from './sensitivity';
import type { ElementBounds } from './dom';
import type { RedactionDecision, SanitizedElement } from './redaction';
import type { VisualBoundingBox } from './visual';

/**
 * Finding source in the unified privacy pipeline.
 */
export type FindingSource = 'dom' | 'visual' | 'correlated';

/**
 * A unified finding combining DOM and visual scan discoveries.
 *
 * PRIVACY CONTRACT:
 * - Must NEVER contain secret values, raw textContent of sensitive fields, or OCR text.
 */
export interface UnifiedFinding {
  id: string;
  source: FindingSource;
  category: SensitiveElementType;
  confidence: number;
  elementId?: string;
  bounds: ElementBounds | VisualBoundingBox;
  decision: RedactionDecision;
  reasons: string[];
  maskToken?: string;
}

/**
 * Visual region summary safe for inclusion in sanitized context.
 */
export interface SanitizedVisualRegion {
  id: string;
  category: SensitiveElementType;
  confidence: number;
  bounds: VisualBoundingBox;
  decision: RedactionDecision;
}

/**
 * The final unified sanitized context generated by the privacy firewall.
 * This is the ONLY object that passes across the firewall outbound boundary.
 */
export interface UnifiedSanitizedContext {
  pageUrl: string;
  pageTitle: string;
  timestamp: number;
  elements: SanitizedElement[];
  visualRegions: SanitizedVisualRegion[];
  unifiedFindings: UnifiedFinding[];
  summary: {
    totalElements: number;
    totalVisualFindings: number;
    totalSensitiveRegions: number;
    redactedCount: number;
    blockedCount: number;
    unknownCount: number;
    allowedControls: number;
  };
  redactionCoverage: number;
  isFailClosed: boolean;
  failureReason?: string;
}
